# Generated by Django 5.0.1 on 2024-03-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hospital_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=122)),
            ],
        ),
    ]
